language: c
sudo: true
before_install:
    - brew update || sudo apt-get update -yqq
    - brew install valgrind || sudo apt-get install -yqq valgrind
    - git clone https://github.com/alelievr/libft-unit-test.git
    - sed -i.bak "s#\.\.\/libft\$#\.\.\/\.#" libft-unit-test/Makefile
matrix:
    include:
        - os: osx
          compiler: gcc
          env: CXX=gcc
        - os: osx
          compiler: clang
          env: CXX=clang
        - os: linux
          compiler: gcc
          env: CXX=gcc
        - os: linux
          compiler: clang
          env: CXX=clang
    allow_failures:
        - os: linux
          compiler: gcc
          env: CXX=gcc
        - os: linux
          compiler: clang
          env: CXX=clang
script: make CC=$CXX -C libft-unit-test; cd libft-unit-test; cp ../libft.* .; valgrind ./run_test; ./run_test
