language: c
compiler:
    - gcc
    - clang
os:
    - osx
    - linux
before_install:
    - git clone https://github.com/alelievr/libft-unit-test.git
    - sed -i.bak "s#\.\.\/libft$#\.\.\/\.#" libft-unit-test/Makefile
matrix:
    allow_failures:
        - os: linux
script: make CC=$CXX -C libft-unit-test && cd libft-unit-test && ./run_test
